binCount = 401  # number of bins for the grid (standard would be 201)
timeScaleFactorFile = "scaleFactorTime.csv"  # file that stores the time-scale factor-relation for the SM case
initialX = 0.1  # start point of the integration, use 0.1 for LLPs
finalX = 35  # 20 is enough for LLPs, though this is not significantly changing the runtime
parameterFile = "parameters.csv"  # file that lists all sets of parameters
useDecayProbabilities = True  # if set to false decayProbabilities referenced in parameterFile will be ignored
endInjection = True  # cuts the injection at a given multiple of the lifetime should be turned on for LLPs
debugOutput = False   # debug output keep it turned off, if you don't want to flood the command line output
ifDebugging = False  # when True, compute the nu-self collision term twice and subtract its energy moment from dz/dx
outputFileTemplate = "result_{idx}.txt"  #  pattern for the result filename from the calculation.
SMComovingLimit = 40  # in MeV lowest maximum comoving momentum, that can be chosen